version: '3.7'
services:
  hawking-api:
    container_name: hawking-api
    build: 
      context: ./api
    ports:
      - 3001:3000
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - elasticsearch
      - hawking-kibana
    networks:
      - hawking-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "false"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data   
    networks:
      - hawking-network 
  hawking-kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - hawking-network
      
volumes:
  esdata:
    driver: local

networks:
  hawking-network:
    driver: bridge


