version: '3.7'
services:
  hawking-api:
    container_name: hawking-api
    build: 
      context: ./api
    ports:
      - 3001:3000
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - elasticsearch
      - hawking-kibana
    networks:
      - hawking-network
  hawking-elasticsearch-seed:
    container_name: hawking-elasticsearch-seed
    command: sh wait_to_start.sh
    build: 
      context: ./elastic-seed
    volumes:
      - ./elastic-seed:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - elasticsearch
    networks:
      - hawking-network
    environment:
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://elastic:9200/_cat/health?h=st) = 200 ]
      - WAIT_START_CMD=python access_elastic_search.py
      - WAIT_SLEEP=2
      - WAIT_LOOPS=10
  elasticsearch:
    container_name: hawking-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "false"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data   
    networks:
      - hawking-network 
  hawking-kibana:
    container_name: hawking-kibana
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - hawking-network
      
volumes:
  esdata:
    driver: local

networks:
  hawking-network:
    driver: bridge


