version: '3.7'
services:
  hawking-api:
    container_name: hawking-api
    build: 
      context: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - elasticsearch
    networks:
      - hawking-network
  hawking-front:
    container_name: hawking-front
    build: 
      context: ./front
    ports:
      - 3001:3001
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - hawking-api
    networks:
      - hawking-network
  elasticsearch:
    container_name: hawking-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail -u elastic:admin localhost:9200/_cat/health?h=st || exit 1"]
      interval: 50s
      timeout: 30s
      retries: 5
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.templates.enabled: "true"
      ELASTIC_PASSWORD: "admin"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data   
    networks:
      - hawking-network 
  # hawking-kibana:
  #   container_name: hawking-kibana
  #   image: docker.elastic.co/kibana/kibana:8.1.0
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  #     ELASTICSEARCH_USERNAME: "admin3"
  #     ELASTICSEARCH_PASSWORD: "admin123"
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - hawking-network

networks:
  hawking-network:
    
volumes:
  esdata:
    driver: local

